parameters:
#    atomic_blog.example.class: Atomic\BlogBundle\Example

services:
#    atomic_blog.example:
#        class: %atomic_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
