<?php

namespace Atomic\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IconomyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IconomyRepository extends EntityRepository {



    public function createQueryBuilder($alias) {
        return $this->_em->createQueryBuilder()
                        ->select($alias)
                        ->from($this->_entityName, $alias);
    }

}
