<?php

namespace Atomic\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MoneyLoggerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoneyLoggerRepository extends EntityRepository
{
}
