services:
      md5_password_encoder:
        class: Atomic\UserBundle\Encoder\Md5Encoder
        
security:   
        
    encoders:
        FOS\UserBundle\Model\UserInterface: { id: md5_password_encoder }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
             id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                use_referer:        true
            logout:       true
            anonymous:    true
            

