<?php

namespace Atomic\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends EntityRepository {

    public $paginator = null;

    public function getLatestBlogs($limit = null) {
        $qb = $this->createQueryBuilder('b')
                ->select('b')
                ->addOrderBy('b.created', 'DESC');

        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()
                        ->getResult();
    }

    public function getPaginatorBlog() {

        if (!isset($this->paginator)) {
            $query = $this->createQueryBuilder('b')
                    ->select('b')
                    ->addOrderBy('b.created', 'DESC');

            $this->paginator = new Paginator($query, $fetchJoinCollection = true);
        }
        return $this->paginator;
    }

    public function getBlogPage($page, $limit = 5) {
        $paginator = $this->getPaginatorBlog();
        $paginator
                ->getQuery()
                ->setFirstResult($limit * ($page-1))
                ->setMaxResults($limit);

        return $paginator;
    }

    public function createQueryBuilder($alias) {
        return $this->_em->createQueryBuilder()
                        ->select($alias)
                        ->from($this->_entityName, $alias);
    }

}
