parameters:
#    atomic_map.example.class: Atomic\MapBundle\Example

services:
#    atomic_map.example:
#        class: %atomic_map.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
