atomic_api_topcraft_vote:
    pattern:  /topcraft/vote
    defaults: { _controller: AtomicApiBundle:Topcraft:vote }
    requirements:
        _method:  POST    

atomic_api_permissions_delete_expired:
    pattern:  /permissions/delete-exprired
    defaults: { _controller: AtomicApiBundle:Permissions:deleteExpired }
