<?php

namespace Atomic\MainMenuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository {

    public function getMenu() {
        $qb = $this->createQueryBuilder('m')
                ->select('m')
                ->addOrderBy('m.ordering', 'ASC');

       
        $menu = $qb->getQuery()
                        ->getResult();
        return $menu;
    }

    public function createQueryBuilder($alias) {
        return $this->_em->createQueryBuilder()
                        ->select($alias)
                        ->from($this->_entityName, $alias);
    }
    
   

}
