<?php

namespace Atomic\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PermissionsEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermissionsEntityRepository extends EntityRepository
{
}
