<?php

namespace Atomic\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PermissionsInheritanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermissionsInheritanceRepository extends EntityRepository
{
}
