<?php

namespace Atomic\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SkinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkinRepository extends EntityRepository
{
}
